### ISSUE TITLE
Implement createPortal API

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [developit/preact-compat#452]
https://reactjs.org/docs/portals.html

**Comment by developit** [comment]
Likely doable via preact-portal

**Comment by jeberly** [comment]
This is causing problems when trying to leverage https://ant.design/

**Comment by jachicao** [comment]
Also material-ui

**Comment by developit** [comment]
This is #1 on the todo list.

**Comment by ducwings** [comment]
also in 'reactstrap`

```
61:13-25 "export 'createPortal' was not found in 'react-dom'
 @ ./node_modules/react-portal/es/Portal.js
 @ ./node_modules/react-portal/es/PortalCompat.js
 @ ./node_modules/react-portal/es/index.js
 @ ./node_modules/reactstrap/dist/reactstrap.es.js```

**Comment by samtheprogram** [comment]
I took a swing at implementing this (very naively), but no success; render fails with `<undefined></undefined>` output. I'm going to take a deeper look and also set up a smaller project to reproduce a test environment.

If there's anyway to get a stack trace on an undefined tag, that would be helpful, but I assume the only reason that's not happening is because the root of the issue comes from the custom code in preact-compat that I've added.

**Comment by marvinhagemeister** [comment]
When you enable the debug tools you have callback where you can make custom assertions on each `vnode` object. It has a check if the tag is `undefined` already built-in. That should help :)

**Comment by eveningkid** [comment]
So actually, quick question: is it only related to `preact-compat` or `preact` itself? I'm still thinking about switching to preact.
 
Would the same error show up without using the compatibility layer but preact directly? Thanks!

**Comment by developit** [comment]
@samtheprogram hiya! Mind joining our chat?
https://preact-slack.now.sh

**Comment by samtheprogram** [comment]
Hey @developit, I've joined under the same username as my GitHub account!

**Comment by ev-dev** [comment]
Also breaks compatibility with searchkit (elasticsearch component library) with the same error of export createPortal not found in react-dom. I assume all use of the Portal API is not currently available

**Comment by Kanaye** [comment]
Hey @Madhu0.
I updated your example code to use a wrapper component to pass the context.
You find it [here](https://preactjs.com/repl?code=const%20%20%7B%20h%2C%20render%2C%20Component%20%7D%20%3D%20preact%3B%0A%0Aclass%20ContextProvider%20extends%20Component%20%7B%0A%09getChildContext()%20%7B%0A%09%09return%20this.props.context%3B%0A%09%7D%0A%09render()%20%7B%0A%09%09return%20this.props.children%20%20%26%26%20this.props.children%5B0%5D%3B%0A%09%7D%0A%7D%0A%0Aclass%20BaseModal%20extends%20Component%20%7B%0A%0A%09renderChildren()%20%7B%0A%09%09return%20(%0A%09%09%09%3Cdiv%20id%3D%7Bthis.id%7D%3E%0A%09%09%09%09%3CContextProvider%20context%3D%7Bthis.context%7D%3E%0A%09%09%09%09%20%20%7Bthis.props.children%7D%0A%09%09%09%09%3C%2FContextProvider%3E%0A%09%09%09%3C%2Fdiv%3E%0A%09%09)%3B%0A%09%7D%0A%0A%09constructor(props)%20%7B%0A%09%09super(props)%3B%0A%09%09this.id%20%3D%20(new%20Date()).getTime()%20%2B%20%27%27%3B%0A%09%09this.element%20%3D%20%27%27%3B%0A%09%7D%0A%0A%09componentDidMount()%20%7B%0A%09%09const%20%7B%20children%20%7D%20%3D%20this.props%3B%0A%09%20%20this.target%20%3D%20document.querySelector(this.props.target)%3B%0A%09%09this.element%20%3D%20render(this.renderChildren()%2C%20this.target)%3B%0A%09%7D%0A%0A%09componentDidUpdate()%20%7B%0A%09%09this.element%20%3D%20render(this.renderChildren()%2C%20this.target%2C%20this.element)%3B%0A%09%7D%0A%0A%09componentWillUnmount()%20%7B%0A%09%09const%20element%20%3D%20this.element%3B%0A%09%09if%20(element%20%26%26%20element.parentElement)%20%7B%0A%09%09%09element.parentElement.removeChild(this.element)%3B%0A%09%09%7D%0A%09%7D%0A%0A%09render()%20%7B%0A%09%09return%20%3Cdiv%20%2F%3E%3B%0A%09%7D%0A%7D%0A%0Aclass%20Test%20extends%20Component%20%7B%0A%09%09getChildContext()%20%7B%0A%09%09%09return%20%7B%0A%09%09%09%20some%3A%20%22Context%22%0A%09%09%09%7D%3B%0A%09%09%7D%0A%20%20%20%20render()%7B%0A%20%20%20%20%20%20%20%20return(%3CBaseModal%20target%3D%22%23mymodal%22%3E%7Bthis.props.children%7D%3C%2FBaseModal%3E)%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20ContextPrinter%20extends%20Component%20%7B%0A%09render()%20%7B%0A%09%09return%20(%0A%09%09%09%3Cpre%3E%0A%09%09%7BJSON.stringify(this.context)%7D%0A%09%09%09%3C%2Fpre%3E%0A%09%09)%3B%0A%09%7D%0A%7D%0A%0Aconst%20App%20%3D%20()%20%3D%3E%20(%0A%09%3Cdiv%3E%09%09%0A%09%09%3Cdiv%20id%3D%22mymodal%22%20style%3D%22border%3A%201px%20solid%20%23000%3B%22%3E%3C%2Fdiv%3E%0A%09%09%3Cp%3ESome%20content%20asdf%3C%2Fp%3E%0A%09%09%3CTest%3E%0A%09%09%09%3CContextPrinter%20%2F%3E%0A%09%09%3C%2FTest%3E%0A%09%3C%2Fdiv%3E%0A)%3B%0A%0Aexport%20default%20App%3B) in the preact repl.

**Comment by Madhu0** [comment]
Hey @Kanaye, this works. Thank you for your time.

If we can provide props and context to the component which will be mounted somewhere outside our actual app, aren't we achieving everything React.createPortal does? am i missing something?

I am trying to understand the portal implementation in react, i've gone through createPortal source code and i wasn't able to understand completely. But the basic idea is, it should work just like any other component inside our app, right?

We can even use `render(App, target, previousApp)` to find the diff in DOM and update, instead of deleting it and rendering it again.

**Comment by developit** [comment]
@Madhu0 around 90% of it, yes. They also redirect event bubbling through portal boundaries, which Preact is unlikely to ever do.

**Comment by ar1a** [comment]
This is causing an issue with react-md,

```
./node_modules/react-md/es/Helpers/Portal.js
11:23-35 'react-dom' does not contain an export named 'createPortal'.

```

**Comment by armand1m** [comment]
is there any thing we can do while this is not implemented?

**Comment by mozillo** [comment]
Same issue with react-select
```
'react-dom' does not contain an export named 'createPortal'
```

**Comment by developit** [comment]
If anyone wants to PR the implementation, something like this would work:

```js
import { h } from 'preact';
import Portal from 'preact-portal';

export function createPortal(child, container) {
  return <Portal into={container}>{child}</Portal>
}
```

**Comment by developit** [comment]
nevermind, there was a much smaller and simpler way and I've implemented it in #486. If anyone has time to test it out that would be lovely.

**Comment by ray-kim-12** [comment]
I'm getting the same error about 'createPortal' above.
I know it's not yet released, but I've copied the updates for 'createPortal' from `https://github.com/developit/preact-compat/blob/master/src/index.js` but am still getting this error:
```
129:12-33 "export 'createPortal' (imported as 'ReactDOM') was not found in 'react-dom'
```
What am I missing?
